/**:
  ros__parameters:
    can_interfaces_json: '[{"name": "can0", "baudrate": "500000", "vesc_ids": [{"id": "1", "label": "front_left"}, {"id": "2", "label": "front_right"}, {"id": "3", "label": "rear_left"}, {"id": "4", "label": "rear_right"}]}]'
    publish_rate: 100.0